name: fizzia_ei
description: A new Flutter project for sensor access and Arabic localization.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Sensors
  sensors_plus: ^5.0.0
  permission_handler: ^11.0.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^24.1.41

  # State & Nav
  get: ^4.6.6

  # Localization
  intl: ^0.19.0

  # File formats & Export
  csv: ^6.0.0
  pdf: ^3.10.4
  image: ^4.1.3
  share_plus: ^9.0.0

  # UI
  flutter_settings_ui: ^2.0.1
  cupertino_icons: ^1.0.2

  # Audio
  just_audio: ^0.9.36
  fft: ^0.1.3

  # Firebase
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
